In [13]:
import pandas as pd

# Path to the original Excel file
file_path = r'2025_01_29_combined_table_implementation.xlsm'

# Path for the new Excel file
output_file_path = r'dynamic4.xlsx'

# Name of the sheet to process
sheet_name = "MFA_Template_collection"

# Read the sheet into a DataFrame
df = pd.read_excel(file_path, sheet_name=sheet_name)
print(df)

   Name of the sample(Flow)  \
0       Generic Information
1                       NaN
2                       NaN
3                       NaN
4                       NaN
5              Generic Data
6                       NaN
7                       NaN
8                       NaN
9                       NaN
10                      NaN
11     Material Composition
12                      NaN
13                      NaN
14                      NaN
15                      NaN
16                      NaN
17                      NaN
18                      NaN
19                      NaN
20                      NaN
21                      NaN
22                      NaN
23                      NaN
24                      NaN
25                      NaN
26                      NaN
27                      NaN
28                      NaN
29                      NaN
30                      NaN
31                      NaN
32                      NaN
33                      NaN
34                      NaN
35                      NaN
36                      NaN
37                      NaN
38                      NaN
39                      NaN
40                      NaN
41                      NaN
42                      NaN
43                      NaN
44                      NaN
45                      NaN
46                      NaN
47                      NaN
48                      NaN
49                      NaN
50                      NaN
51                      NaN
52                      NaN
53                      NaN
54                      NaN
55                      NaN
56                      NaN

                                           Unnamed: 1  \
0                                    Stakeholder Name
1                                            Location
2                                                Date
3                                        Process name
4                                        Process type
5                                                 NaN
6                                                 NaN
7                                              Amount
8                                       Contamination
9                                  Moisture Condition
10                                                NaN
11                             Nane of material types
12                                                NaN
13  This list includes commonly used material name...
14                                 PP materials in DS
15                                PET materials in DS
16                               Film materials in DS
17                               HDPE materials in DS
18                                 MP materials in DS
19                                 PS materials in DS
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN
28                                                NaN
29                                                NaN
30                                                NaN
31                                                NaN
32                                                NaN
33                                                NaN
34                                                NaN
35                                                NaN
36                                                NaN
37                                                NaN
38                                                NaN
39                                                NaN
40                                                NaN
41                                                NaN
42                                                NaN
43                                                NaN
44                                                NaN
45                                                NaN
46                                                NaN
47                                                NaN
48                                                NaN
49                                                NaN
50                                                NaN
51                                                NaN
52                                                NaN
53                                                NaN
54                                                NaN
55                                                NaN
56                                             others

       Plastics in Different DS             Unnamed: 3  \
0                    Mar Daniel                    NaN
1                  TU Darmstadt                    NaN
2                    10.12.2024                    NaN
3                           NaN                    NaN
4                    Collection                    NaN
5                         Value                   Unit
6                        Amount             best in SI
7                        1198.7                    ton
8                           NaN                    NaN
9                           NaN                    NaN
10                          NaN                    NaN
11                      wt(dry)       Unit of wt (dry)
12                          NaN                    NaN
13  weight in the dry condition  Allowed: ton,kg, g, %
14                        295.6                    ton
15                        199.5                    ton
16                          386                    ton
17                        197.9                    ton
18                           63                    ton
19                         56.7                    ton
20                          NaN                    NaN
21                          NaN                    NaN
22                          NaN                    NaN
23                          NaN                    NaN
24                          NaN                    NaN
25                          NaN                    NaN
26                          NaN                    NaN
27                          NaN                    NaN
28                          NaN                    NaN
29                          NaN                    NaN
30                          NaN                    NaN
31                          NaN                    NaN
32                          NaN                    NaN
33                          NaN                    NaN
34                          NaN                    NaN
35                          NaN                    NaN
36                          NaN                    NaN
37                          NaN                    NaN
38                          NaN                    NaN
39                          NaN                    NaN
40                          NaN                    NaN
41                          NaN                    NaN
42                          NaN                    NaN
43                          NaN                    NaN
44                          NaN                    NaN
45                          NaN                    NaN
46                          NaN                    NaN
47                          NaN                    NaN
48                          NaN                    NaN
49                          NaN                    NaN
50                          NaN                    NaN
51                          NaN                    NaN
52                          NaN                    NaN
53                          NaN                    NaN
54                          NaN                    NaN
55                          NaN                    NaN
56                          NaN                    NaN

                                           Unnamed: 4             Unnamed: 5  \
0                                                 NaN                    NaN
1                                                 NaN                    NaN
2                                                 NaN                    NaN
3                                                 NaN                    NaN
4                                                 NaN                    NaN
5                                            Comments                    NaN
6   Provide additional observations, notes, or exc...                    NaN
7                                                 NaN                    NaN
8                                                 NaN                    NaN
9                                                 NaN                    NaN
10                                                NaN                    NaN
11                                            wt(wet)       Unit of wt (wet)
12                                                NaN                    NaN
13                        weight in the wet condition  Allowed: ton,kg, g, %
14                                                NaN                    NaN
15                                                NaN                    NaN
16                                                NaN                    NaN
17                                                NaN                    NaN
18                                                NaN                    NaN
19                                                NaN                    NaN
20                                                NaN                    NaN
21                                                NaN                    NaN
22                                                NaN                    NaN
23                                                NaN                    NaN
24                                                NaN                    NaN
25                                                NaN                    NaN
26                                                NaN                    NaN
27                                                NaN                    NaN
28                                                NaN                    NaN
29                                                NaN                    NaN
30                                                NaN                    NaN
31                                                NaN                    NaN
32                                                NaN                    NaN
33                                                NaN                    NaN
34                                                NaN                    NaN
35                                                NaN                    NaN
36                                                NaN                    NaN
37                                                NaN                    NaN
38                                                NaN                    NaN
39                                                NaN                    NaN
40                                                NaN                    NaN
41                                                NaN                    NaN
42                                                NaN                    NaN
43                                                NaN                    NaN
44                                                NaN                    NaN
45                                                NaN                    NaN
46                                                NaN                    NaN
47                                                NaN                    NaN
48                                                NaN                    NaN
49                                                NaN                    NaN
50                                                NaN                    NaN
51                                                NaN                    NaN
52                                                NaN                    NaN
53                                                NaN                    NaN
54                                                NaN                    NaN
55                                                NaN                    NaN
56                                                NaN                    NaN

                         Unnamed: 6                        Unnamed: 7  \
0                               NaN                               NaN
1                               NaN                               NaN
2                               NaN                               NaN
3                               NaN                               NaN
4                               NaN                               NaN
5                               NaN                               NaN
6                               NaN                               NaN
7                               NaN                               NaN
8                               NaN                               NaN
9                               NaN                               NaN
10                              NaN                               NaN
11                  Density [kg/m3]                             Color
12                              NaN                               NaN
13   measured data of this sample,   color of this material componant
14                              NaN                               NaN
15                              NaN                               NaN
16                              NaN                               NaN
17                              NaN                               NaN
18                              NaN                               NaN
19                              NaN                               NaN
20                              NaN                               NaN
21                              NaN                               NaN
22                              NaN                               NaN
23                              NaN                               NaN
24                              NaN                               NaN
25                              NaN                               NaN
26                              NaN                               NaN
27                              NaN                               NaN
28                              NaN                               NaN
29                              NaN                               NaN
30                              NaN                               NaN
31                              NaN                               NaN
32                              NaN                               NaN
33                              NaN                               NaN
34                              NaN                               NaN
35                              NaN                               NaN
36                              NaN                               NaN
37                              NaN                               NaN
38                              NaN                               NaN
39                              NaN                               NaN
40                              NaN                               NaN
41                              NaN                               NaN
42                              NaN                               NaN
43                              NaN                               NaN
44                              NaN                               NaN
45                              NaN                               NaN
46                              NaN                               NaN
47                              NaN                               NaN
48                              NaN                               NaN
49                              NaN                               NaN
50                              NaN                               NaN
51                              NaN                               NaN
52                              NaN                               NaN
53                              NaN                               NaN
54                              NaN                               NaN
55                              NaN                               NaN
56                              NaN                               NaN

                                        Unnamed: 8
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4                                              NaN
5                                              NaN
6                                              NaN
7                                              NaN
8                                              NaN
9                                              NaN
10                                             NaN
11                                       Reference
12                                             NaN
13  Data measured/estinated,  measurement errors,
14                                             NaN
15                                             NaN
16                                             NaN
17                                             NaN
18                                             NaN
19                                             NaN
20                                             NaN
21                                             NaN
22                                             NaN
23                                             NaN
24                                             NaN
25                                             NaN
26                                             NaN
27                                             NaN
28                                             NaN
29                                             NaN
30                                             NaN
31                                             NaN
32                                             NaN
33                                             NaN
34                                             NaN
35                                             NaN
36                                             NaN
37                                             NaN
38                                             NaN
39                                             NaN
40                                             NaN
41                                             NaN
42                                             NaN
43                                             NaN
44                                             NaN
45                                             NaN
46                                             NaN
47                                             NaN
48                                             NaN
49                                             NaN
50                                             NaN
51                                             NaN
52                                             NaN
53                                             NaN
54                                             NaN
55                                             NaN
56                                             NaN

In [14]:
df

,Name of the sample(Flow),Unnamed: 1,Plastics in Different DS,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Generic Information,Stakeholder Name,Mar Daniel,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Location,TU Darmstadt,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Date,10.12.2024,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Process name,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Process type,Collection,NaN,NaN,NaN,NaN,NaN,NaN
5,Generic Data,NaN,Value,Unit,Comments,NaN,NaN,NaN,NaN
6,NaN,NaN,Amount,best in SI,"Provide additional observations, notes, or exc...",NaN,NaN,NaN,NaN
7,NaN,Amount,1198.7,ton,NaN,NaN,NaN,NaN,NaN
8,NaN,Contamination,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Moisture Condition,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Material Composition,Nane of material types,wt(dry),Unit of wt (dry),wt(wet),Unit of wt (wet),Density [kg/m3],Color,Reference
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,This list includes commonly used material name...,weight in the dry condition,"Allowed: ton,kg, g, %",weight in the wet condition,"Allowed: ton,kg, g, %","measured data of this sample,",color of this material componant,"Data measured/estinated, measurement errors,"
14,NaN,PP materials in DS,295.6,ton,NaN,NaN,NaN,NaN,NaN
15,NaN,PET materials in DS,199.5,ton,NaN,NaN,NaN,NaN,NaN
16,NaN,Film materials in DS,386,ton,NaN,NaN,NaN,NaN,NaN
17,NaN,HDPE materials in DS,197.9,ton,NaN,NaN,NaN,NaN,NaN
18,NaN,MP materials in DS,63,ton,NaN,NaN,NaN,NaN,NaN
19,NaN,PS materials in DS,56.7,ton,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,others,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
import pandas as pd

# Path to the original Excel file
file_path = r'C:\Users\Master.WR\OneDrive - stud.tu-darmstadt.de\Documents\Fraunhofer\2025_01_29_combined_table_implementation.xlsm'


# Path for the new Excel file
output_file_path =r'C:\Users\Master.WR\OneDrive - stud.tu-darmstadt.de\Documents\Fraunhofer\dynamic6.xlsx'


# Name of the sheet to process
sheet_name = "MFA_Template_collection"

# Read the sheet into a DataFrame
df = pd.read_excel(file_path, sheet_name=sheet_name, header=0)  # Include headers

# Extract the "Material Name" from the column names
material_name = df.columns[2]  # Extract the header value for Column 3 (index 2)

# Extract relevant rows for "Name of the Materials" and "Amount"
materials_df = df.iloc[14:30, [1, 2]]  # Rows 15–25 (indices 14–24), Columns B and C

# Rename the columns for clarity
materials_df.columns = ["Name of the Materials", "Amount"]

# Remove rows with blank values in the "Name of the Materials" or "Amount" columns
materials_df = materials_df.dropna(subset=["Name of the Materials", "Amount"])

# Add the "Name of the sheet" and "Material name" columns to the extracted data
materials_df["Name of the sheet"] = sheet_name
materials_df["Material name"] = material_name

# Reorder columns to match the desired format
materials_df = materials_df[["Name of the sheet", "Material name", "Name of the Materials", "Amount"]]

# Write the resulting DataFrame to a new Excel file
materials_df.to_excel(output_file_path, index=False)

print(f"New Excel file has been created with the header name: {output_file_path}")

New Excel file has been created with the header name: C:\Users\Master.WR\OneDrive - stud.tu-darmstadt.de\Documents\Fraunhofer\dynamic6.xlsx

In [2]:
import pandas as pd

# Path to the original Excel file
file_path =  r'2025_01_29_combined_table_implementation.xlsm'

# Path for the final combined Excel file
output_file_path =  r'combined_excel_from_all_sheets.xlsx'

# List of sheet names to process (provide the names here)
# sheet_names = [
#     "MFA_Template_collection",  # Add other sheet names here
#     "MFA_Template_sorting_flow_1",   # Example sheet names
#     "MFA_Template_sorting_flow_2_PP",
#     "MFA_Template_sorting_flow_2_PS",
#     "MFA_Template_sorting_flow_2_PET",
#     "MFA_Template_sorting_flow_2_HDP",
#     "MFA_Template_sorting_flow_2_Fil"

#     # Add all other required sheet names here
# ]

sheet_names = [
    "MFA_Template_collection",  # Add other sheet names here
    "MFA_Template_sorting_flow_2_PP",
    "MFA_Template_sorting_flow_2_PS",
    "MFA_Template_sorting_flow_2_PET",
    "MFA_Template_sorting_flow_2_HDP",
    "MFA_Template_sorting_flow_2_Fil"

    # Add all other required sheet names here
]

# Initialize an empty DataFrame to hold all data
combined_data = pd.DataFrame()

# Loop through each sheet
for sheet_name in sheet_names:
    # Read the current sheet into a DataFrame
    df = pd.read_excel(file_path, sheet_name=sheet_name, header=0)
    
    # Extract the "Material Name" from the column names
    material_name = df.columns[2]  # Extract header of the third column (Column C in Excel)

    # Extract relevant rows for "Name of the Materials" and "Amount"
    materials_df = df.iloc[14:30, [1, 2]]  # Rows 15–25 (indices 14–24), Columns B and C
    
    # Rename the columns for clarity
    materials_df.columns = ["Name of the Materials", "Amount"]
    
    # Remove rows with blank values in the "Name of the Materials" or "Amount" columns
    materials_df = materials_df.dropna(subset=["Name of the Materials", "Amount"])
    
    # Add the "Name of the sheet" and "Material name" columns to the extracted data
    materials_df["Name of the sheet"] = sheet_name
    materials_df["Material name"] = material_name
    
    # Reorder columns to match the desired format
    materials_df = materials_df[["Name of the sheet", "Material name", "Name of the Materials", "Amount"]]
    
    # Append the current sheet's data to the combined DataFrame
    combined_data = pd.concat([combined_data, materials_df], ignore_index=True)

# Write the combined data to a new Excel file
combined_data.to_excel(output_file_path, index=False)

print(f"Combined Excel file has been created: {output_file_path}")

Combined Excel file has been created: combined_excel_from_all_sheets.xlsx

In [3]:
df = pd.read_excel(output_file_path)

In [5]:
df = df.drop(columns=["Name of the sheet"])

In [6]:
df

                   Material name        Name of the Materials         Amount
0       Plastics in Different DS           PP materials in DS          295.6
1       Plastics in Different DS          PET materials in DS          199.5
2       Plastics in Different DS         Film materials in DS            386
3       Plastics in Different DS         HDPE materials in DS          197.9
4       Plastics in Different DS           MP materials in DS             63
5       Plastics in Different DS           PS materials in DS           56.7
6       PP in PP sorted products            PP food packaging           21.2
7       PP in PP sorted products           Mix food packaging           10.3
8       PP in PP sorted products        PE non-food packaging            1.1
9       PP in PP sorted products        PP non-food packaging           12.1
10      PP in PP sorted products                     PP trays            3.8
11      PP in PP sorted products               Black plastics              2
12      PP in PP sorted products               Foils ≥ DIN A4              2
13      PP in PP sorted products               Foils < DIN A4            5.3
14      PP in PP sorted products       Non Packaging Plastics             17
15      PP in PP sorted products         Packaging Composites            1.3
16      PP in PP sorted products              Residues coarse            1.2
17      PP in PP sorted products                 Fine < 40 mm            4.7
18      PP in PP sorted products            Moisture and dirt  15.4% ± 11.0%
19      PS in PS sorted products           Mix food packaging            1.9
20      PS in PS sorted products                    PS rigids           42.5
21      PS in PS sorted products                          EPS            1.2
22      PS in PS sorted products        PP non-food packaging           12.1
23      PS in PS sorted products               Black plastics            1.7
24      PS in PS sorted products       Non Packaging Plastics           32.7
25      PS in PS sorted products                 Fine < 40 mm            2.9
26      PS in PS sorted products            Moisture and dirt   12.4% ± 9.9%
27    PET in PET sorted products     PET food packaging clear           19.1
28    PET in PET sorted products  PET food packaging coloured            5.2
29    PET in PET sorted products          Mix food packaginga           17.5
30    PET in PET sorted products       PET non-food packaging           15.8
31    PET in PET sorted products                    PET trays             17
32    PET in PET sorted products               Black plastics            1.6
33    PET in PET sorted products               Foils < DIN A4            1.5
34    PET in PET sorted products       Non Packaging Plastics            2.4
35    PET in PET sorted products         Packaging Composites            2.1
36    PET in PET sorted products                 Fine < 40 mm            1.8
37    PET in PET sorted products            Moisture and dirt   11.4% ± 3.8%
38  HDPE in HDPE sorted products            PE food packaging            6.4
39  HDPE in HDPE sorted products        PE non-food packaging           62.6
40  HDPE in HDPE sorted products               Black plastics            2.3
41  HDPE in HDPE sorted products               Foils < DIN A4            2.5
42  HDPE in HDPE sorted products       Non Packaging Plastics           12.4
43  HDPE in HDPE sorted products         Packaging Composites            1.1
44  HDPE in HDPE sorted products                 Fine < 40 mm            2.5
45  HDPE in HDPE sorted products            Moisture and dirt    6.8% ± 3.1%
46  Film in film sorted products               Black plastics            1.1
47  Film in film sorted products               Foils ≥ DIN A4           46.6
48  Film in film sorted products               Foils < DIN A4           23.2
49  Film in film sorted products       Non Packaging Plastics            3.8
50  Film in film sorted products            Moisture and dirt   19.8% ± 6.9%

In [8]:
# Create a dictionary to store annotation texts keyed by the label (from "Material name")
annotations_dict = {}

# Process each row in the dataframe
for index, row in df.iterrows():
    # Get the label from the "Material name" column
    label = row["Material name"]
    
    # Get the values for annotation: "Name of the Materials" and "Amount"
    material_value = str(row["Name of the Materials"])
    amount_value = str(row["Amount"]).strip()  # Convert to string and remove any leading/trailing spaces
    
    # If the amount does not end with "%", append it.
    if not amount_value.endswith("%"):
        amount_value += "%"
    
    # Build the annotation text for this row
    text_line = f"{material_value}: {amount_value}"
    
    # If this label is already in our dictionary, append the text on a new line;
    # otherwise, add a new entry.
    if label in annotations_dict:
        annotations_dict[label] += "\n" + text_line
    else:
        annotations_dict[label] = text_line

# For verification, print out the resulting dictionary
# print(annotations_dict)

In [9]:
annotations_dict

{'Plastics in Different DS': 'PP materials in DS: 295.6%\nPET materials in DS: 199.5%\nFilm materials in DS: 386%\nHDPE materials in DS: 197.9%\nMP materials in DS: 63%\nPS materials in DS: 56.7%',
 'PP in PP sorted products': 'PP food packaging: 21.2%\nMix food packaging: 10.3%\nPE non-food packaging: 1.1%\nPP non-food packaging: 12.1%\nPP trays: 3.8%\nBlack plastics: 2%\nFoils ≥ DIN A4: 2%\nFoils < DIN A4: 5.3%\nNon Packaging Plastics: 17%\nPackaging Composites: 1.3%\nResidues coarse: 1.2%\nFine < 40 mm: 4.7%\nMoisture and dirt: 15.4% ± 11.0%',
 'PS in PS sorted products': 'Mix food packaging: 1.9%\nPS rigids: 42.5%\nEPS: 1.2%\nPP non-food packaging: 12.1%\nBlack plastics: 1.7%\nNon Packaging Plastics: 32.7%\nFine < 40 mm: 2.9%\nMoisture and dirt: 12.4% ± 9.9%',
 'PET in PET sorted products': 'PET food packaging clear: 19.1%\nPET food packaging coloured: 5.2%\nMix food packaginga: 17.5%\nPET non-food packaging: 15.8%\nPET trays: 17%\nBlack plastics: 1.6%\nFoils < DIN A4: 1.5%\nNon Packaging Plastics: 2.4%\nPackaging Composites: 2.1%\nFine < 40 mm: 1.8%\nMoisture and dirt: 11.4% ± 3.8%',
 'HDPE in HDPE sorted products': 'PE food packaging: 6.4%\nPE non-food packaging: 62.6%\nBlack plastics: 2.3%\nFoils < DIN A4: 2.5%\nNon Packaging Plastics: 12.4%\nPackaging Composites: 1.1%\nFine < 40 mm: 2.5%\nMoisture and dirt: 6.8% ± 3.1%',
 'Film in film sorted products': 'Black plastics: 1.1%\nFoils ≥ DIN A4: 46.6%\nFoils < DIN A4: 23.2%\nNon Packaging Plastics: 3.8%\nMoisture and dirt: 19.8% ± 6.9%'}

In [10]:
# Create a dictionary to store annotation texts keyed by the label (from "Material name")
annotations_dict = {}

# Process each row in the dataframe
for index, row in df.iterrows():
    # Get the label from the "Material name" column
    label = row["Material name"]
    
    # Get the values for annotation: "Name of the Materials" and "Amount"
    material_value = str(row["Name of the Materials"])
    amount_value = str(row["Amount"]).strip()  # Convert to string and remove any extra spaces
    
    # If the amount does not end with "%", append it.
    if not amount_value.endswith("%"):
        amount_value += "%"
    
    # Build the annotation text for this row
    text_line = f"{material_value}: {amount_value}"
    
    # If this label is already in our dictionary, append the text with a <br>;
    # otherwise, start with the label in bold and then add the text.
    if label in annotations_dict:
        annotations_dict[label] += "<br>" + text_line
    else:
        annotations_dict[label] = f"<b>{label}</b><br>" + text_line

# For verification, print out the resulting dictionary
annotations_dict

{'Plastics in Different DS': '<b>Plastics in Different DS</b><br>PP materials in DS: 295.6%<br>PET materials in DS: 199.5%<br>Film materials in DS: 386%<br>HDPE materials in DS: 197.9%<br>MP materials in DS: 63%<br>PS materials in DS: 56.7%',
 'PP in PP sorted products': '<b>PP in PP sorted products</b><br>PP food packaging: 21.2%<br>Mix food packaging: 10.3%<br>PE non-food packaging: 1.1%<br>PP non-food packaging: 12.1%<br>PP trays: 3.8%<br>Black plastics: 2%<br>Foils ≥ DIN A4: 2%<br>Foils < DIN A4: 5.3%<br>Non Packaging Plastics: 17%<br>Packaging Composites: 1.3%<br>Residues coarse: 1.2%<br>Fine < 40 mm: 4.7%<br>Moisture and dirt: 15.4% ± 11.0%',
 'PS in PS sorted products': '<b>PS in PS sorted products</b><br>Mix food packaging: 1.9%<br>PS rigids: 42.5%<br>EPS: 1.2%<br>PP non-food packaging: 12.1%<br>Black plastics: 1.7%<br>Non Packaging Plastics: 32.7%<br>Fine < 40 mm: 2.9%<br>Moisture and dirt: 12.4% ± 9.9%',
 'PET in PET sorted products': '<b>PET in PET sorted products</b><br>PET food packaging clear: 19.1%<br>PET food packaging coloured: 5.2%<br>Mix food packaginga: 17.5%<br>PET non-food packaging: 15.8%<br>PET trays: 17%<br>Black plastics: 1.6%<br>Foils < DIN A4: 1.5%<br>Non Packaging Plastics: 2.4%<br>Packaging Composites: 2.1%<br>Fine < 40 mm: 1.8%<br>Moisture and dirt: 11.4% ± 3.8%',
 'HDPE in HDPE sorted products': '<b>HDPE in HDPE sorted products</b><br>PE food packaging: 6.4%<br>PE non-food packaging: 62.6%<br>Black plastics: 2.3%<br>Foils < DIN A4: 2.5%<br>Non Packaging Plastics: 12.4%<br>Packaging Composites: 1.1%<br>Fine < 40 mm: 2.5%<br>Moisture and dirt: 6.8% ± 3.1%',
 'Film in film sorted products': '<b>Film in film sorted products</b><br>Black plastics: 1.1%<br>Foils ≥ DIN A4: 46.6%<br>Foils < DIN A4: 23.2%<br>Non Packaging Plastics: 3.8%<br>Moisture and dirt: 19.8% ± 6.9%'}