In [1]:
pip install pandas openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\mdshadmanhasan\appdata\roaming\python\python310\site-packages (2.0.3)
Requirement already satisfied: openpyxl in e:\anaconda3\lib\site-packages (3.0.10)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mdshadmanhasan\appdata\roaming\python\python310\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\mdshadmanhasan\appdata\roaming\python\python310\site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\mdshadmanhasan\appdata\roaming\python\python310\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\mdshadmanhasan\appdata\roaming\python\python310\site-packages (from pandas) (1.26.4)
Requirement already satisfied: et_xmlfile in e:\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\mdshadmanhasan\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd

In [28]:
df = pd.read_excel('combined_summary_4.xlsx')

In [29]:
df

,Process Name,Input Material Name,Input Material Amount,Output Material Name,Output Material Amount
0,Process_collection,Plastics in Households,2170.3,PET Deposit,425.0
1,NaN,NaN,NaN,Plastics in Different DS,1198.7
2,NaN,NaN,NaN,Waste,538.1
3,Process_sorting_flow_1,Plastics in Different DS,1198.7,Mixed Plastics,419.0
4,NaN,NaN,NaN,PP-flow,186.2
5,NaN,NaN,NaN,PS-flow,38.9
6,NaN,NaN,NaN,PET-flow,147.0
7,NaN,NaN,NaN,HDPE-flow,104.9
8,NaN,NaN,NaN,Film-flow,302.7
9,Process_sorting_flow_2_PP,PP-flow,186.2,PP in PP sorted Products,106.9
10,NaN,NaN,NaN,PP in other sorted products,79.3
11,Process_recycling_PP,PP in PP sorted Products,106.9,Food PP,33.4
12,NaN,NaN,NaN,Non-food PP,19.6
13,NaN,NaN,NaN,Mixed Packaging PP,15.0
14,NaN,NaN,NaN,Trays PP,6.5
15,NaN,NaN,NaN,MaD PP,26.2
16,NaN,NaN,NaN,PP recycling residues,6.1

In [30]:
df = df.fillna(method='ffill')

In [31]:
df

,Process Name,Input Material Name,Input Material Amount,Output Material Name,Output Material Amount
0,Process_collection,Plastics in Households,2170.3,PET Deposit,425.0
1,Process_collection,Plastics in Households,2170.3,Plastics in Different DS,1198.7
2,Process_collection,Plastics in Households,2170.3,Waste,538.1
3,Process_sorting_flow_1,Plastics in Different DS,1198.7,Mixed Plastics,419.0
4,Process_sorting_flow_1,Plastics in Different DS,1198.7,PP-flow,186.2
5,Process_sorting_flow_1,Plastics in Different DS,1198.7,PS-flow,38.9
6,Process_sorting_flow_1,Plastics in Different DS,1198.7,PET-flow,147.0
7,Process_sorting_flow_1,Plastics in Different DS,1198.7,HDPE-flow,104.9
8,Process_sorting_flow_1,Plastics in Different DS,1198.7,Film-flow,302.7
9,Process_sorting_flow_2_PP,PP-flow,186.2,PP in PP sorted Products,106.9
10,Process_sorting_flow_2_PP,PP-flow,186.2,PP in other sorted products,79.3
11,Process_recycling_PP,PP in PP sorted Products,106.9,Food PP,33.4
12,Process_recycling_PP,PP in PP sorted Products,106.9,Non-food PP,19.6
13,Process_recycling_PP,PP in PP sorted Products,106.9,Mixed Packaging PP,15.0
14,Process_recycling_PP,PP in PP sorted Products,106.9,Trays PP,6.5
15,Process_recycling_PP,PP in PP sorted Products,106.9,MaD PP,26.2
16,Process_recycling_PP,PP in PP sorted Products,106.9,PP recycling residues,6.1

In [32]:
# Extract values from the first row (row index 0)
node_label_1 = df.iloc[0, 0]  # Value at position (0,0)
node_label_2 = df.iloc[0, 1]  # Value at position (0,1)
link_value   = df.iloc[0, 2]  # Value at position (0,2)

# Create the nodes part:
# Since you want a list of nodes (each node being a dictionary with a 'label' key)
nodes = [
    {'label': node_label_1},
    {'label': node_label_2}
]

# Create the link part:
# Each link is a dictionary with 'source', 'target', and 'value'
links = [
    {
        'source': node_label_1,  # from the value at (0,0)
        'target': node_label_2,  # from the value at (0,1)
        'value': link_value      # from the value at (0,2)
    }
]

In [33]:
nodes

[{'label': 'Process_collection'}, {'label': 'Plastics in Households'}]

In [34]:
links

[{'source': 'Process_collection',
  'target': 'Plastics in Households',
  'value': 2170.3}]

In [35]:
df = df.drop(columns=['Process Name', 'Input Material Amount'])

In [36]:
df

,Input Material Name,Output Material Name,Output Material Amount
0,Plastics in Households,PET Deposit,425.0
1,Plastics in Households,Plastics in Different DS,1198.7
2,Plastics in Households,Waste,538.1
3,Plastics in Different DS,Mixed Plastics,419.0
4,Plastics in Different DS,PP-flow,186.2
5,Plastics in Different DS,PS-flow,38.9
6,Plastics in Different DS,PET-flow,147.0
7,Plastics in Different DS,HDPE-flow,104.9
8,Plastics in Different DS,Film-flow,302.7
9,PP-flow,PP in PP sorted Products,106.9
10,PP-flow,PP in other sorted products,79.3
11,PP in PP sorted Products,Food PP,33.4
12,PP in PP sorted Products,Non-food PP,19.6
13,PP in PP sorted Products,Mixed Packaging PP,15.0
14,PP in PP sorted Products,Trays PP,6.5
15,PP in PP sorted Products,MaD PP,26.2
16,PP in PP sorted Products,PP recycling residues,6.1

In [37]:
node_labels = {node_label_1, node_label_2}

In [38]:
for idx, row in df.iterrows():
    src = row[0]  # first column as source
    tgt = row[1]  # second column as target
    val = row[2]  # third column as link value

    # Check and add the source node if not already present
    if src not in node_labels:
        nodes.append({'label': src})
        node_labels.add(src)

    # Check and add the target node if not already present
    if tgt not in node_labels:
        nodes.append({'label': tgt})
        node_labels.add(tgt)

    # Append the link from source to target with the given value
    links.append({
        'source': src,
        'target': tgt,
        'value': val
    })

In [39]:
nodes

[{'label': 'Process_collection'},
 {'label': 'Plastics in Households'},
 {'label': 'PET Deposit'},
 {'label': 'Plastics in Different DS'},
 {'label': 'Waste'},
 {'label': 'Mixed Plastics'},
 {'label': 'PP-flow'},
 {'label': 'PS-flow'},
 {'label': 'PET-flow'},
 {'label': 'HDPE-flow'},
 {'label': 'Film-flow'},
 {'label': 'PP in PP sorted Products'},
 {'label': 'PP in other sorted products'},
 {'label': 'Food PP'},
 {'label': 'Non-food PP'},
 {'label': 'Mixed Packaging PP'},
 {'label': 'Trays PP'},
 {'label': 'MaD PP'},
 {'label': 'PP recycling residues'}]

In [40]:
links

[{'source': 'Process_collection',
  'target': 'Plastics in Households',
  'value': 2170.3},
 {'source': 'Plastics in Households', 'target': 'PET Deposit', 'value': 425.0},
 {'source': 'Plastics in Households',
  'target': 'Plastics in Different DS',
  'value': 1198.7},
 {'source': 'Plastics in Households', 'target': 'Waste', 'value': 538.1},
 {'source': 'Plastics in Different DS',
  'target': 'Mixed Plastics',
  'value': 419.0},
 {'source': 'Plastics in Different DS', 'target': 'PP-flow', 'value': 186.2},
 {'source': 'Plastics in Different DS', 'target': 'PS-flow', 'value': 38.9},
 {'source': 'Plastics in Different DS', 'target': 'PET-flow', 'value': 147.0},
 {'source': 'Plastics in Different DS', 'target': 'HDPE-flow', 'value': 104.9},
 {'source': 'Plastics in Different DS', 'target': 'Film-flow', 'value': 302.7},
 {'source': 'PP-flow', 'target': 'PP in PP sorted Products', 'value': 106.9},
 {'source': 'PP-flow', 'target': 'PP in other sorted products', 'value': 79.3},
 {'source': 'PP in PP sorted Products', 'target': 'Food PP', 'value': 33.4},
 {'source': 'PP in PP sorted Products',
  'target': 'Non-food PP',
  'value': 19.6},
 {'source': 'PP in PP sorted Products',
  'target': 'Mixed Packaging PP',
  'value': 15.0},
 {'source': 'PP in PP sorted Products', 'target': 'Trays PP', 'value': 6.5},
 {'source': 'PP in PP sorted Products', 'target': 'MaD PP', 'value': 26.2},
 {'source': 'PP in PP sorted Products',
  'target': 'PP recycling residues',
  'value': 6.1}]

In [41]:
import plotly.graph_objects as go

In [42]:
# ------------------------------------
# Step 1: Prepare Data for Plotly Sankey
# ------------------------------------
# Create a list of node labels (the order matters for indices)
node_labels = [node['label'] for node in nodes]

# Create a mapping from node label to its index in the node_labels list
label_to_index = {label: idx for idx, label in enumerate(node_labels)}

# Convert link information to use node indices rather than labels
source_indices = [label_to_index[link['source']] for link in links]
target_indices = [label_to_index[link['target']] for link in links]
values = [link['value'] for link in links]

# ------------------------------------
# Step 2: Create the Sankey Diagram with Plotly
# ------------------------------------
fig = go.Figure(data=[go.Sankey(
    node=dict(
        pad=15,
        thickness=20,
        line=dict(color="black", width=0.5),
        label=node_labels,
        color="blue"
    ),
    link=dict(
        source=source_indices,  # List of source node indices
        target=target_indices,  # List of target node indices
        value=values,           # List of link values
        color="gray"
    )
)])

fig.update_layout(title_text="Sankey Diagram", font_size=10)
fig.show()